### ISSUE TITLE
Doesn't work with woocommerce lost-password endpoint

### ISSUE THREAD

**Issue by cycomarcooo** [codehaiku/subway-2.0#20]
Woocommerce lost-password endpoint is not whitelisted. 
Should be useful to add a check like this one inside PageRedirect::index() : 

```
// Check if woocommerce lost-password page.
if ( class_exists( 'WooCommerce' ) ) {
    if ( is_wc_endpoint_url( 'lost-password' ) ) {
        return;
    }
}
```

**Comment by codehaiku** [comment]
hi, cyco! That's actually a clever way to check if the page is woocommerce lost password page. Subway should work with WooCommerce lost password page by default, the user just need to add the ID of 'my-accounts' page to the Subway public pages ID.

But I'll add that so that users won't be needing to add the accounts page ID manually, can you pull request?

Thanks!

**Comment by cycomarcooo** [comment]
Hi, you are right about the my-account ID but it allows access to all endpoints (not very critical if the use is not logged-in by the way). I'll create a pull request asap.

**Comment by codehaiku** [comment]
@cycomarcooo I'm going to mark this close for the meantime. Just pull request anytime 👍  

Thank you!
